### ISSUE TITLE
SW Map Request

### ISSUE THREAD

**Issue by KateTheCat** [altonchaney/cosmere-maps#3]
Not an issue, but do you plan to include the paths of characters from SW Rebels in your maps? If not, can I ask where you got your data for the other installments? I've been looking for a list of planets visited in SW Rebels for a while. Do you just take notes while watching, or is there a list somewhere?

**Comment by KateTheCat** [comment]
Oh, I can see that I posted this on the wrong repository. Um, I guess you should know that the help link on the star wars map goes here instead of the sw map repository.

**Comment by altonchaney** [comment]
I've updated the link in that project and will track this issue there going forward, thank you for calling that out.
