### ISSUE TITLE
Chapters Cut off on SA Maps

### ISSUE THREAD

**Issue by Curc8** [altonchaney/cosmere-maps#6]
Once the chapter numbers go past a certain point on the map they are cut off and I can no longer click on them. Maybe I'm missing some feature to scroll through the chapter numbers, but so far there's nothing I've tried that has worked.

**Comment by altonchaney** [comment]
Yep I'll take a look at this over the next few days and see what's going on

**Comment by altonchaney** [comment]
I've made the scrollbars visible across the board so you should be able to use your mouse to control the horizontal scrolling on the map timeline now. Thanks for calling that out! I'll try to make the scrollbar visibility more 'specific' but for now I've err'ed on the side of accessibility so it'll be visible everywhere.
