### ISSUE TITLE
Oathbringer character path suggestion

### ISSUE THREAD

**Issue by cperezf** [altonchaney/cosmere-maps#8]
<details><summary>Spoiler warning until the end of Oathbringer chapter 34 </summary>
<p>

Tha map updates Jasnah way to Urithiru in chapter 32 without visiting the Shattered Plains. However, in chapter 34 Jasnah mentions going through the war camps, presumably arriving at Urithiru via the Oathgate in the plains. Just saying in case you might like to update her path according to that.

</p>
</details> 

PS: Great work with the map! Wonderful experience to visualy track every character throughout my rereads to get ready for Wind and Truth.

**Comment by altonchaney** [comment]
Ah thank you! I will adjust her path accordingly

**Comment by altonchaney** [comment]
I've updated her path for that chapter, thanks for the call out. If you notice anything else off just let me know!
